#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
  path: /login
  methods: ['POST']

login_refresh_token:
  path: /login/refresh_token
  controller: gesdinet.jwtrefreshtoken::refresh

metadata:
  path: /metadata
  controller: App\Controller\MetadataController::getMetadata
  methods:  ['get']
