- name: php bin/console
  command: '{{ item }}'
  args:
      chdir: '{{ deploy_helper.new_release_path }}'
  with_items:
      - '{{ php_version }} bin/console doctrine:schema:update --force'
      - '{{ php_version }} bin/console cache:clear'
